version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  cache:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/unicorn
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file: .env

volumes:
  postgres_data: