[tool.poetry]
name = "unicorn-backend"
version = "7.0.0"
description = "Unified Net-based Interface for Competition Organization, Rules and News."
authors = ["Core:Systemstøtte <support@gathering.org>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "~4.2.6"
djangorestframework = "~3.14.0"
django-cors-headers = "~4.2.0"
django-debug-toolbar = "~4.2.0"
django-filter = "~23.3"
django-guardian = "~2.4.0"
djangorestframework-guardian = "==0.3.0"
django-oauth-toolkit = "~2.3.0"
drf-writable-nested = "==0.7.0"
gunicorn = "~21.2.0"
pytz = ">=2023.3,<2024.0"
python-dateutil = ">=2.8.2,<3.0"
social-auth-app-django = "^5.3.0"
django-environ = "~0.11.2"
django-tailwind = "==3.4.0"
drf-spectacular = "~0.26.5"
django-redis = "~5.4.0"
pillow = ">=9.2,<10.0"
django-auditlog = "~2.3.0"
psycopg = {extras = ["binary"], version = "^3.1.12"}


[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
unittest2 = "^1.1.0"
black = "^23.9.1"

[build-system]
# Remember to also update in Dockerfile and Github Workflow
requires = ["poetry-core==1.6.1"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.black]
line-length = 120
exclude = '''
/(
  | migrations
)/
'''