[tool.poetry]
name = "unicorn-backend"
version = "7.0.0"
description = "Unified Net-based Interface for Competition Organization, Rules and News."
authors = ["Core:Systemstøtte <support@gathering.org>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
dj-database-url = ">=1.0.0,<2.0"
django = "^4.1.6"
djangorestframework = "^3.14.0"
django-cors-headers = ">=3.13,<3.14"
django-debug-toolbar = ">=3.7,<3.8"
django-filter = ">=22.1,<23.0"
django-guardian = ">=2.4,<2.5"
djangorestframework-guardian = "==0.3.0"
django-multiselectfield = "==0.1.12"
django-oauth-toolkit = ">=2.2.0,<2.3.0"
drf-writable-nested = "==0.7.0"
gunicorn = ">=20.1,<21.0"
psycopg2-binary = ">=2.9.4,<3.0"
pytz = ">=2022.4,<2023.0"
sentry-sdk = ">=1.9.10,<2.0"
python-dateutil = ">=2.8.2,<3.0"
social-auth-app-django = ">=5.0,<6.0"
django-environ = "==0.9.0"
django-tailwind = "==3.4.0"
drf-spectacular = ">=0.25,<0.26"
django-redis = ">=5.2,<6.0"
pillow = ">=9.2,<10.0"


[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
unittest2 = "^1.1.0"
black = "^23.1.0"

[build-system]
# Remember to also update in Dockerfile and Github Workflow
requires = ["poetry-core==1.3.2"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.black]
line-length = 120
exclude = '''
/(
  | migrations
)/
'''